#ifndef GLOBAL_HOTKEY_GLOBAL_HOTKEY_DISABLE_HOOK_FWD_HPP
#define GLOBAL_HOTKEY_GLOBAL_HOTKEY_DISABLE_HOOK_FWD_HPP

#define GLOBAL_HOTKEY_DISABLE_HOOK

#include "global_hotkey.hpp"

#endif // !GLOBAL_HOTKEY_GLOBAL_HOTKEY_DISABLE_HOOK_FWD_HPP
